from dataclasses import dataclass
from typing import Callable, Optional

import numpy as np
import scipy.stats as stats

from utils.montecarlo import *


LogPDF = Callable[[np.ndarray], float] # log f(x)
LogCondPDF = Callable[[np.ndarray, np.ndarray, np.ndarray], float] # log q(y|x) 
ProposalSampler = Callable[[np.ndarray, np.ndarray], np.ndarray]  # sample y ~ q(· | x)

@dataclass
class MCMCResultBase:
    """
    Base container for MCMC output.
    
    Attributes
    ----------
    samples : np.ndarray
        Array of generated samples with shape (N, d).
    accept_rate : float
        Overall acceptance rate of the chain.
    accept_mask : np.ndarray
        Boolean mask of length N indicating accepted proposals.
    """
    samples: np.ndarray
    accept_rate: float
    accept_mask: np.ndarray


@dataclass
class MHResult(MCMCResultBase):
    """
    Result object for the Metropolis-Hastings algorithm.
    Inherits the standard MCMC fields without modification.
    """
    pass


def mh_acceptance_prob(
    current_target_logpdf_value : float,
    proposed_target_logpdf_value : float,
    current_sample: np.ndarray,
    proposed_sample: np.ndarray,
    proposal_logpdf_conditional: LogCondPDF,
    proposal_sampler_cov: np.ndarray) -> float:
    """
    Compute the Metropolis-Hastings acceptance probability for a proposed move. 
    
    Parameters
    ----------
    current_target_logpdf_value : float
        The log of the target density evaluated at the current state x,
        i.e log f(x)
    proposed_target_logpdf_value : float
        The log of the target density evaluated at the proposed state y,
        i.e log f(y)
    current_sample: np.ndarray
        current state x (d,) of the markov chain
    proposed_sample: np.ndarray
        proposed state y (d,) of the markov chain
    proposal_logpdf_conditional:  Callable[[np.ndarray, np.ndarray], float]
        A function that returns log q(y | x, cov), the log-density of proposing
        `second` from `first`. Used to compute q(y|x) and q(x|y).
        
    Returns
    -------
    float
        The MH acceptance probability a(x, y), equal to:
            min(1, exp(log f(y) + log q(x|y) - log f(x) - log q(y|x))).
    """
    
    #1) Compute Forward Probability flow logf(x) - log q(y|x)
    forward_prob_flow = current_target_logpdf_value + \
        proposal_logpdf_conditional(proposed_sample, current_sample, proposal_sampler_cov)
        
    #2) Compute Reverse Probability flow logf(y) - log q(x|y)
    reverse_prob_flow = proposed_target_logpdf_value + \
        proposal_logpdf_conditional(current_sample, proposed_sample, proposal_sampler_cov)
    # 3) log acceptance ratio
    log_acceptance_prob = reverse_prob_flow - forward_prob_flow
    
    # 4) Acceptance Probability
    acceptance_prob = np.exp(log_acceptance_prob)
    return min(1.0, acceptance_prob)



def mh_mcmc(
    initial_sample: np.ndarray,
    initial_cov: np.ndarray,
    num_samples: int,
    target_logpdf: LogPDF,
    proposal_logpdf: LogCondPDF,
    proposal_sampler: ProposalSampler) -> MHResult:
    """
    Run the Metropolis-Hastings MCMC algorithm to generate samples from a 
    target distribution defined by its log-density.

    Parameters
    ----------
    initial_sample : np.ndarray
        Initial state of the Markov chain, shape (d,). This is stored as 
        the first sample X_0.
    num_samples : int
        Total number of samples to generate (including the initial sample).
    target_logpdf : LogPDF
        Function returning log f(x), the log-density of the target distribution.
        Signature: target_logpdf(x: np.ndarray) -> float.
    proposal_logpdf : LogCondPDF
        Function returning log q(y | x), the conditional proposal log-density 
        used in the MH acceptance ratio.
        Signature: proposal_logpdf(y: np.ndarray, x: np.ndarray) -> float.
    proposal_sampler : ProposalSampler
        Function that generates a proposed point y from the current point x,
        i.e. y ~ q(· | x, cov).
        Signature: proposal_sampler(x: np.ndarray) -> np.ndarray.

    Returns
    -------
    MHSamples
        A dataclass containing:
        
        samples : np.ndarray
            Array of all samples generated by the chain, shape (num_samples, d).
        
        acceptance_rate : float
            Fraction of proposed moves that were accepted, computed as:
                acceptance_count / (num_samples - 1).
    """
    
    # dimension of the state space
    d = initial_sample.shape[0]
    
    # allocate array for samples: shape (num_samples, d)
    samples = np.zeros((num_samples, d))
    
    # store inital sample
    samples[0] = initial_sample
    
    # acceptance mask
    acceptance_mask = np.zeros(num_samples, dtype=bool)
    
    eps= 0.001
    sd = 2.4**2/float(d)
    S0 = sd* initial_cov + sd* eps * np.identity(d)
    Sk = S0
    
    current_sample = initial_sample
    acceptance_count = 0
    for i in range(1, num_samples):
        # 1) Propose a sample y ~ q(.|x, Sk)
        proposed_sample = proposal_sampler(current_sample, Sk)
        
        # 2) compute log f(x) and log f(y)
        current_target_logpdf_value = target_logpdf(current_sample)
        proposed_target_logpdf_value = target_logpdf(proposed_sample)
        
        # 3) Compute acceptance probability a(x,y)
        acceptance_prob = mh_acceptance_prob(
            current_target_logpdf_value,
            proposed_target_logpdf_value,
            current_sample,
            proposed_sample,
            proposal_logpdf,
            Sk)
        
        # 4) Accept Proposed or Reject and take current 
        u = np.random.rand()
        
        if u < acceptance_prob:
            # Accept the Proposed Sample
            samples[i] = proposed_sample
            acceptance_count += 1
            acceptance_mask[i] = True
        else:
            # Reject and take current Sample
            samples[i] = current_sample
            acceptance_mask[i] = False
        
        current_sample = samples[i]
    
    # 5) Return 
    return MHResult(
            samples=samples,
            accept_rate= acceptance_count/float(num_samples-1),
            accept_mask=acceptance_mask)
        